name: Build and Deploy Documentation

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install packages
        run: |
          python -m pip install sphinx sphinx-book-theme
      - name: Build documentation
        run: |
          make html
        working-directory: ./doc
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./doc/build/html
